services:
  auth-service:
    build:
      context: ../
      dockerfile: Dockerfile
      secrets:
        - dev_db_password
    ports:
      - '8080:8080'
    networks:
      - auth-net
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD_FILE: /run/secrets/dev_db_password
      DB_NAME: authservicelocal
      DB_SSL_MODE: disable
      REDIS_ARGS: --save 1200 32
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      REDIS_URL: redis://redis:6379
    secrets:
      - dev_db_password
      - redis_password
    depends_on:
      postgres-dev:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgres-dev:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD_FILE: /run/secrets/dev_db_password
      POSTGRES_DB: authservicelocal
    secrets:
      - dev_db_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d
    networks:
      - auth-net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d authservicelocal']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack:7.2.0-v17
    environment:
      REDIS_ARGS: --save 1200 32
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    secrets:
      - redis_password
    command: redis-server --requirepass /run/secrets/redis_password
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    networks:
      - auth-net
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
  redis_data:

secrets:
  dev_db_password:
    file: ../scripts/cockroach/certs/.dev_db_password
  redis_password:
    file: ../scripts/cockroach/certs/.redis_password
networks:
  auth-net:
    driver: bridge
