services:
  auth-service:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '8080:8080'
    environment:
      - APP_ENV=production
      - DB_HOST=lb
      - DB_PORT=26257
    networks:
      - auth-net
    depends_on:
      lb:
        condition: service_healthy
    secrets:
      - source: ca.crt
        target: /app/cockroach/certs/ca.crt
      - source: client.appuser.crt
        target: /app/cockroach/certs/client.appuser.crt
      - source: client.appuser.key
        target: /app/cockroach/certs/client.appuser.key

networks:
  auth-net:
    external: true
    driver: bridge

secrets:
  ca.crt:
    file: ../scripts/cockroach/certs/ca.crt
  client.appuser.crt:
    file: ../scripts/cockroach/certs/client.appuser.crt
  client.appuser.key:
    file: ../scripts/cockroach/certs/client.appuser.key
