# dev.yml
database:
  mysql_dsn: "appuser:${DEV_DB_PASSWORD:-dev_db_password}@tcp(localhost:3388)/authservicelocal?parseTime=true"
  host: "localhost"
  port: 3388
  user: "appuser"
  password: ${DEV_DB_PASSWORD:-dev_db_password}
  dbname: "authservicelocal"
  sslmode: disable
  migrate: true

redis:
  redis_addr: "localhost:6388"
  redis_password: "${REDIS_PASSWORD:-redis_password}"
