# File: authentication-service/internal/configs/dev.yml

database:
  host: "localhost"
  port: 26257
  user: "root"
  name: "authservicelocal"
  sslmode: "verify-full"
  sslrootcert: "./cockroach/certs/ca.crt"
  sslcert: "./cockroach/certs/client.root.crt"
  sslkey: "./cockroach/certs/client.root.key"
  migrate: true