# prod.yml
database:
  mysql_dsn: "appuser:${PROD_DB_PASSWORD:-prod_db_password}@tcp(mysql-prod:3306)/authserviceprod?parseTime=true"
  host: "mysql-prod"
  port: 3306
  user: "appuser"
  password: ${PROD_DB_PASSWORD:-prod_db_password}
  dbname: "authserviceprod"
  sslmode: require
  migrate: true

redis:
  redis_addr: "redis:6379"
  redis_password: "${REDIS_PASSWORD:-redis_password}"