# prod.yml
database:
  host: "lb"
  port: 26257
  user: "appuser"
  name: "authserviceprod"
  sslmode: "verify-full"
  sslrootcert: "/run/secrets/ca.crt"
  sslcert: "/run/secrets/client.auth_user.crt"
  sslkey: "/run/secrets/client.auth_user.key"
  migrate: false