// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/abisalde/authentication-service/internal/database/ent/useraddress"
)

// UserAddress is the model entity for the UserAddress schema.
type UserAddress struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserAddress) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case useraddress.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserAddress fields.
func (ua *UserAddress) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case useraddress.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ua.ID = int(value.Int64)
		default:
			ua.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserAddress.
// This includes values selected through modifiers, order, etc.
func (ua *UserAddress) Value(name string) (ent.Value, error) {
	return ua.selectValues.Get(name)
}

// Update returns a builder for updating this UserAddress.
// Note that you need to call UserAddress.Unwrap() before calling this method if this UserAddress
// was returned from a transaction, and the transaction was committed or rolled back.
func (ua *UserAddress) Update() *UserAddressUpdateOne {
	return NewUserAddressClient(ua.config).UpdateOne(ua)
}

// Unwrap unwraps the UserAddress entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ua *UserAddress) Unwrap() *UserAddress {
	_tx, ok := ua.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserAddress is not a transactional entity")
	}
	ua.config.driver = _tx.drv
	return ua
}

// String implements the fmt.Stringer.
func (ua *UserAddress) String() string {
	var builder strings.Builder
	builder.WriteString("UserAddress(")
	builder.WriteString(fmt.Sprintf("id=%v", ua.ID))
	builder.WriteByte(')')
	return builder.String()
}

// UserAddresses is a parsable slice of UserAddress.
type UserAddresses []*UserAddress
