package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/abisalde/authentication-service/internal/graph/model"
)

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context) (*model.User, error) {
	return r.profileHandler.GetUserProfile(ctx)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, role *model.UserRole, first *int32, after *string) (*model.UserConnection, error) {
	var firstID *int
	if first != nil {
		val := int(*first)
		firstID = &val
	}

	return r.usersHandler.GetAllUsers(ctx, role, firstID, after)
}

// CheckUsernameAvailability is the resolver for the checkUsernameAvailability field.
func (r *queryResolver) CheckUsernameAvailability(ctx context.Context, username string) (*model.UsernameAvailability, error) {
	available, err := r.authService.CheckUsernameAvailability(ctx, username)
	if err != nil {
		return nil, err
	}

	return &model.UsernameAvailability{
		Available: available,
		Username:  username,
	}, nil
}
